name: Reproduce makefile executions

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Code execution
      run: |
        make run
    - name: Build & Push Docker Image
      run: |
        make docker